const FASTWPAY = {
  id: 0,
  siteUrl: 'https://fastwpay.com',
  image: '/assets/companiesLogos/fastwpay.svg',
  name: 'Fastwpay',
  domain: 'fastwpay.com',
  description:
    'Fastwpay es una pagina web dedicada al manejo administrativo de un plugin de wordpress para pagos electronicos.',
  isASingleProject: true,
  projectImages: [
    '/assets/projects_images/fastywpay/Hero.png',
    '/assets/projects_images/fastywpay/the-best-pay-solution.png',
    '/assets/projects_images/fastywpay/how-to-install-activate.png',
    '/assets/projects_images/fastywpay/remember-to-install.png',
    '/assets/projects_images/fastywpay/free-to-install.png',
    '/assets/projects_images/fastywpay/countries-where-it-work.png',
    '/assets/projects_images/fastywpay/contact-form.png',
    '/assets/projects_images/fastywpay/login.png',
    '/assets/projects_images/fastywpay/signup.png',
    '/assets/projects_images/fastywpay/recover-password.png',
    '/assets/projects_images/fastywpay/dashboard.png',
    '/assets/projects_images/fastywpay/generate-api-key.png',
    '/assets/projects_images/fastywpay/list-api-key.png',
    '/assets/projects_images/fastywpay/account.png',
    '/assets/projects_images/fastywpay/not-found.png',
  ],
};

const WCAR = {
  id: 1,
  siteUrl: 'https://wcar.com',
  image: '/assets/companiesLogos/wcar.svg',
  name: 'wcar',
  domain: 'wcar.co',
  description: '',
  isASingleProject: false,
  projects: [
    {
      id: 11,
      name: 'wcar.co',
      siteUrl: 'https://wcar.com',
      description: 'wcar.co es una plataforma de compra y venta de vehículos usados con peritaje online.',
      projectImages: [
        '/assets/projects_images/wcar/web/home.png',
        '/assets/projects_images/wcar/web/buy_car.png',
        '/assets/projects_images/wcar/web/wanda.png',
        '/assets/projects_images/wcar/web/car_details.png',
        '/assets/projects_images/wcar/web/car_peritaje.png',
        '/assets/projects_images/wcar/web/cotiza.png',
        '/assets/projects_images/wcar/web/credit.png',
        '/assets/projects_images/wcar/web/scheduler.png',
        '/assets/projects_images/wcar/web/taller.png',
        '/assets/projects_images/wcar/web/tramites.png',
        '/assets/projects_images/wcar/web/blog.png',
      ],
      isASingleProject: true,
      overview: 'wcar.co is a platform for buying and selling used vehicles with online appraisal.',
      technologies: ['React', 'Typescript', 'SEO'],
      challenges: 'Developing a platform for buying and selling used vehicles with online appraisal.',
    },
  ],
};

const PORTFOLIO = {
  id: 2,
  siteUrl: 'https://requena.dev',
  image: '/assets/vicLogo_purple.svg',
  name: 'Personal Website',
  domain: 'requena.dev',
};

const NEXTSTATION = {
  id: 3,
  siteUrl: 'https://nextstation.cl',
  image: 'https://s3.amazonaws.com/nextstation.cl/wp-content/uploads/2019/08/27185722/logo-black-45.png',
  name: 'NextStation',
  domain: 'nextstation.cl',
};

const GENIUS = {
  id: 4,
  siteUrl: 'https://geniuspro.io',
  image: '/assets/companiesLogos/genius.svg',
  name: 'Genius',
  domain: '',
  isASingleProject: false,
  projects: [
    {
      id: 41,
      name: 'Genius Builder',
      siteUrl: 'https://genius.builder.io',
      description: '',
      projectImages: [
        '/assets/projects_images/genius/genius-builder/login.png',
        '/assets/projects_images/genius/genius-builder/register.png',
        '/assets/projects_images/genius/genius-builder/forgot-password.png',
        '/assets/projects_images/genius/genius-builder/new-password.png',
        '/assets/projects_images/genius/genius-builder/new-password-successfully.png',
        '/assets/projects_images/genius/genius-builder/terms-privacy-policy.png',
        '/assets/projects_images/genius/genius-builder/how-it-works.png',
        '/assets/projects_images/genius/genius-builder/home.png',
        '/assets/projects_images/genius/genius-builder/plans-pricings.png',
        '/assets/projects_images/genius/genius-builder/faq.png',
        '/assets/projects_images/genius/genius-builder/help.png',
        '/assets/projects_images/genius/genius-builder/my-websites.png',
        '/assets/projects_images/genius/genius-builder/my-websites-2.png',
        '/assets/projects_images/genius/genius-builder/my-websites-4.png',
        '/assets/projects_images/genius/genius-builder/my-websites-3.png',
        '/assets/projects_images/genius/genius-builder/website-creation-1.png',
        '/assets/projects_images/genius/genius-builder/website-creation-2.png',
        '/assets/projects_images/genius/genius-builder/website-creation-3.png',
        '/assets/projects_images/genius/genius-builder/website-creation-3-expanded-view.png',
        '/assets/projects_images/genius/genius-builder/website-creation-3-click-template.png',
        '/assets/projects_images/genius/genius-builder/website-creation-4.png',
        '/assets/projects_images/genius/genius-builder/website-creation-5.png',
        '/assets/projects_images/genius/genius-builder/website-creation-cancel.png',
        '/assets/projects_images/genius/genius-builder/created-successfully-first-time.png',
        '/assets/projects_images/genius/genius-builder/created-successfully.png',
        '/assets/projects_images/genius/genius-builder/website-creation-creator-dashboard.png',
        '/assets/projects_images/genius/genius-builder/website-creation-creator-dashboard-start-video-chat.png',
        '/assets/projects_images/genius/genius-builder/website-creation-creator-dashboard-meeting.png',
        '/assets/projects_images/genius/genius-builder/getting-started.png',
        '/assets/projects_images/genius/genius-builder/webcreator-docs.png',
        '/assets/projects_images/genius/genius-builder/webcreator-do-it-yourself-docs.png',
        '/assets/projects_images/genius/genius-builder/account.png',
        '/assets/projects_images/genius/genius-builder/account-edit.png',
        '/assets/projects_images/genius/genius-builder/account-verify-email.png',
        '/assets/projects_images/genius/genius-builder/notifications.png',
        '/assets/projects_images/genius/genius-builder/not-found.png',
      ],
      isASingleProject: true,
    },
    {
      id: 42,
      name: 'Landing GDS',
      siteUrl: '',
      description: '',
      projectImages: [
        '/assets/projects_images/genius/gds-landing/home.png',
        '/assets/projects_images/genius/gds-landing/home-2.png',
        '/assets/projects_images/genius/gds-landing/learn-more.png',
        '/assets/projects_images/genius/gds-landing/our-team.png',
        '/assets/projects_images/genius/gds-landing/our-products.png',
      ],
      isASingleProject: true,
    },
    {
      id: 43,
      name: 'Lifted Meds',
      siteUrl: '',
      description: '',
      projectImages: [
        '/assets/projects_images/genius/lifted-meds/welcome.png',
        '/assets/projects_images/genius/lifted-meds/welcome-2.png',
        '/assets/projects_images/genius/lifted-meds/welcome-3.png',
        '/assets/projects_images/genius/lifted-meds/location.png',
        '/assets/projects_images/genius/lifted-meds/login.png',
        '/assets/projects_images/genius/lifted-meds/register.png',
        '/assets/projects_images/genius/lifted-meds/reset-password.png',
        // '/assets/projects_images/genius/lifted-meds/shop.png',
        '/assets/projects_images/genius/lifted-meds/shop-2.png',
        '/assets/projects_images/genius/lifted-meds/products.png',
        '/assets/projects_images/genius/lifted-meds/cart.png',
        '/assets/projects_images/genius/lifted-meds/cart-empty.png',
        '/assets/projects_images/genius/lifted-meds/payment-1.png',
        '/assets/projects_images/genius/lifted-meds/payment-1-2.png',
        '/assets/projects_images/genius/lifted-meds/payment-2.png',
        '/assets/projects_images/genius/lifted-meds/payment-3.png',
        '/assets/projects_images/genius/lifted-meds/payment-3-2.png',
        '/assets/projects_images/genius/lifted-meds/payment-3-3.png',
      ],
      isASingleProject: true,
    },
  ],
};

const SL = {
  id: 5,
  siteUrl: 'https://sliscorp.com',
  image: '/assets/companiesLogos/sl.png',
  name: 'SL Innovation & Solutions',
  domain: '',
  isASingleProject: false,
  projects: [
    {
      id: 51,
      name: 'Crop Connect App',
      siteUrl: '',
      description: 'Aplicación móvil para la gestión de cultivos y producción.',
      projectImages: [
        '/assets/projects_images/genius/genius-builder/login.png',
        '/assets/projects_images/genius/genius-builder/register.png',
        '/assets/projects_images/genius/genius-builder/forgot-password.png',
        '/assets/projects_images/genius/genius-builder/new-password.png',
        '/assets/projects_images/genius/genius-builder/new-password-successfully.png',
        '/assets/projects_images/genius/genius-builder/terms-privacy-policy.png',
        '/assets/projects_images/genius/genius-builder/how-it-works.png',
        '/assets/projects_images/genius/genius-builder/home.png',
        '/assets/projects_images/genius/genius-builder/plans-pricings.png',
        '/assets/projects_images/genius/genius-builder/faq.png',
        '/assets/projects_images/genius/genius-builder/help.png',
        '/assets/projects_images/genius/genius-builder/my-websites.png',
        '/assets/projects_images/genius/genius-builder/my-websites-2.png',
        '/assets/projects_images/genius/genius-builder/my-websites-4.png',
        '/assets/projects_images/genius/genius-builder/my-websites-3.png',
        '/assets/projects_images/genius/genius-builder/website-creation-1.png',
        '/assets/projects_images/genius/genius-builder/website-creation-2.png',
        '/assets/projects_images/genius/genius-builder/website-creation-3.png',
        '/assets/projects_images/genius/genius-builder/website-creation-3-expanded-view.png',
        '/assets/projects_images/genius/genius-builder/website-creation-3-click-template.png',
        '/assets/projects_images/genius/genius-builder/website-creation-4.png',
        '/assets/projects_images/genius/genius-builder/website-creation-5.png',
        '/assets/projects_images/genius/genius-builder/website-creation-cancel.png',
        '/assets/projects_images/genius/genius-builder/created-successfully-first-time.png',
        '/assets/projects_images/genius/genius-builder/created-successfully.png',
        '/assets/projects_images/genius/genius-builder/website-creation-creator-dashboard.png',
        '/assets/projects_images/genius/genius-builder/website-creation-creator-dashboard-start-video-chat.png',
        '/assets/projects_images/genius/genius-builder/website-creation-creator-dashboard-meeting.png',
        '/assets/projects_images/genius/genius-builder/getting-started.png',
        '/assets/projects_images/genius/genius-builder/webcreator-docs.png',
        '/assets/projects_images/genius/genius-builder/webcreator-do-it-yourself-docs.png',
        '/assets/projects_images/genius/genius-builder/account.png',
        '/assets/projects_images/genius/genius-builder/account-edit.png',
        '/assets/projects_images/genius/genius-builder/account-verify-email.png',
        '/assets/projects_images/genius/genius-builder/notifications.png',
        '/assets/projects_images/genius/genius-builder/not-found.png',
      ],
      isASingleProject: true,
    },
    {
      id: 52,
      name: 'Banco de Venezuela App',
      siteUrl: '',
      description: 'Aplicación móvil para transacciones bancarias y consultas de finanzas.',
      projectImages: [
        '/assets/projects_images/sl/bdv_app/login.png',
        '/assets/projects_images/sl/bdv_app/dashboard2.png',
        '/assets/projects_images/sl/bdv_app/my_products.png',
        '/assets/projects_images/sl/bdv_app/voucher.png',
        '/assets/projects_images/sl/bdv_app/consultas_menu.png',
        '/assets/projects_images/sl/bdv_app/security_menu.png',
        '/assets/projects_images/sl/bdv_app/mis_finanzas.png',
        '/assets/projects_images/sl/bdv_app/transfer_third_party.png',
        '/assets/projects_images/sl/bdv_app/transfer_confirm.png',
        '/assets/projects_images/sl/bdv_app/mobile_pay_person.png',
        '/assets/projects_images/sl/bdv_app/services_pay.png',
        '/assets/projects_images/sl/bdv_app/directory.png',
        '/assets/projects_images/sl/bdv_app/theme_config.png',
        '/assets/projects_images/sl/bdv_app/claims_point.png',
      ],
      isASingleProject: true,
      type: 'mobile',
      overview:
        'Banco de Venezuela App es una aplicación móvil que permite a los usuarios realizar transacciones bancarias y consultar sus finanzas.',
      technologies: ['React Native', 'Expo'],
      challenges:
        'Desarrollar una aplicación móvil que permita a los usuarios realizar transacciones bancarias y consultar sus finanzas.',
    },
    {
      id: 53,
      name: 'Banco de Venezuela Web',
      siteUrl: '',
      description: 'Aplicación web para transacciones bancarias y consultas de finanzas.',
      projectImages: [
        '/assets/projects_images/genius/lifted-meds/welcome.png',
        '/assets/projects_images/genius/lifted-meds/welcome-2.png',
        '/assets/projects_images/genius/lifted-meds/welcome-3.png',
        '/assets/projects_images/genius/lifted-meds/location.png',
        '/assets/projects_images/genius/lifted-meds/login.png',
        '/assets/projects_images/genius/lifted-meds/register.png',
        '/assets/projects_images/genius/lifted-meds/reset-password.png',
        // '/assets/projects_images/genius/lifted-meds/shop.png',
        '/assets/projects_images/genius/lifted-meds/shop-2.png',
        '/assets/projects_images/genius/lifted-meds/products.png',
        '/assets/projects_images/genius/lifted-meds/cart.png',
        '/assets/projects_images/genius/lifted-meds/cart-empty.png',
        '/assets/projects_images/genius/lifted-meds/payment-1.png',
        '/assets/projects_images/genius/lifted-meds/payment-1-2.png',
        '/assets/projects_images/genius/lifted-meds/payment-2.png',
        '/assets/projects_images/genius/lifted-meds/payment-3.png',
        '/assets/projects_images/genius/lifted-meds/payment-3-2.png',
        '/assets/projects_images/genius/lifted-meds/payment-3-3.png',
      ],
      isASingleProject: true,
    },
    {
      id: 54,
      name: 'Banco Digital de Caracas (IMCP) App',
      siteUrl: '',
      description: 'Aplicación móvil para transacciones bancarias y consultas de finanzas.',
      projectImages: [
        '/assets/projects_images/genius/lifted-meds/welcome.png',
        '/assets/projects_images/genius/lifted-meds/welcome-2.png',
        '/assets/projects_images/genius/lifted-meds/welcome-3.png',
        '/assets/projects_images/genius/lifted-meds/location.png',
        '/assets/projects_images/genius/lifted-meds/login.png',
        '/assets/projects_images/genius/lifted-meds/register.png',
        '/assets/projects_images/genius/lifted-meds/reset-password.png',
        // '/assets/projects_images/genius/lifted-meds/shop.png',
        '/assets/projects_images/genius/lifted-meds/shop-2.png',
        '/assets/projects_images/genius/lifted-meds/products.png',
        '/assets/projects_images/genius/lifted-meds/cart.png',
        '/assets/projects_images/genius/lifted-meds/cart-empty.png',
        '/assets/projects_images/genius/lifted-meds/payment-1.png',
        '/assets/projects_images/genius/lifted-meds/payment-1-2.png',
        '/assets/projects_images/genius/lifted-meds/payment-2.png',
        '/assets/projects_images/genius/lifted-meds/payment-3.png',
        '/assets/projects_images/genius/lifted-meds/payment-3-2.png',
        '/assets/projects_images/genius/lifted-meds/payment-3-3.png',
      ],
      isASingleProject: true,
    },
    {
      id: 55,
      name: 'Banco Digital de Caracas (IMCP) Web',
      siteUrl: '',
      description: 'Aplicación web para transacciones bancarias y consultas de finanzas.',
      projectImages: [],
    },
  ],
};

export const worksDataList = [FASTWPAY, WCAR, PORTFOLIO, NEXTSTATION, GENIUS, SL];

export default {
  FASTWPAY,
  WCAR,
  PORTFOLIO,
  NEXTSTATION,
  GENIUS,
  SL,
};
